# Generated by Django 5.2 on 2025-07-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_post_options_alter_post_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish']},
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
