# Generated by Django 5.2 on 2025-07-03 02:26

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_ticket_alter_post_options_alter_post_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='publish',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(choices=[('SUG', 'suggestions'), ('CRT', 'criticism'), ('REP', 'report')], default=('REP', 'report')),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['name'], name='app1_ticket_name_id_851628_idx'),
        ),
    ]
