# Generated by Django 5.2 on 2025-07-03 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_ticket_options_ticket_publish_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='app1_ticket_name_id_851628_idx',
        ),
    ]
