# Generated by Django 5.2 on 2025-07-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
