# Generated by Django 5.2 on 2025-07-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_post_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
