# Generated by Django 5.2 on 2025-07-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_comment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='app1_commen_name_6b3c1f_idx',
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created'], name='app1_commen_created_637c05_idx'),
        ),
    ]
