# Generated by Django 5.2 on 2025-07-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_comment_app1_commen_name_6b3c1f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
